### PR TITLE
add functions for getting inits

### LINKED ISSUE #29: Proposal: method for retrieving initial parameter estimates
The original motivation stems from [here](https://github.com/metrumresearchgroup/bbr/issues/582#issuecomment-1834615092), though I thought it would be nice to have a neat way to return the initial parameter estimates before this step. Additionally, I think scientists might appreciate the ability to easily retrieve and format initial estimates in some reports, that could be fed into `pmtables` or some other formatting function.

### Requirements
 - For Theta parameters:
    - Must be able to retrieve initial estimates, upper and lower bounds (if any), and whether any of the values are `FIXED`
 - For Matrix-type parameters (OMEGA and SIGMA)
    - Must be able to format all records as a combined matrix if multiple records are found (minus the old method of specifying priors)
    - Must be able to return which indices are `FIXED`. In an offline discussion, it was noted that `FIX` in block matrices fixes the entire record, though specific parameters can be fixed for diagonal matrices. It was suggested that a logical matrix might be the way to go here.
 - Some additional requirements/notes can be found in [this discussion](https://github.com/metrumresearchgroup/bbr/issues/632#issuecomment-1879308199).  

### Initial Prototype
Note that this prototype uses dependencies that would not make sense to utilize in this package; I just used them for nicer formatting in a `bbr` environment. See [this comment](https://github.com/metrumresearchgroup/bbr/pull/635#issuecomment-1885398563) for some examples.

<details closed>
<summary>Code</summary>

```r

#' Retrieve and format the initial estimates
#'
#' @param .mod
#'
#' @export
get_param_inits <- function(.mod){

  test_nmrec_version(.min_version = "0.3.0")
  check_model_object(.mod, "bbi_nonmem_model")


  ctl <- nmrec::read_ctl(get_model_path(.mod))

  recs <- list(
    thetas = nmrec:::create_param_index(ctl, "theta"),
    omegas = nmrec:::create_param_index(ctl, "omega"),
    sigmas = nmrec:::create_param_index(ctl, "sigma")
  )

  recs_values <- list(
    theta = fmt_record_values(param_index = recs$thetas),
    omega = fmt_record_values(param_index = recs$omegas),
    sigma = fmt_record_values(param_index = recs$sigmas)
  )


  return(recs_values)
}


#' Format the initial estimates for each record
#'
#' Matrix type records will be formatted as a block diagonal matrix. Multiple
#' records of the same type will be concatenated diagonally.
#'
#' @param param_index object returned from `create_param_index`.
#'
#' @keywords internal
fmt_record_values <- function(param_index){

  details <- param_index$details
  records <- param_index$records
  name <- param_index$name

  # Only grab initial values for theta bounds
  val_recs <- purrr::map(details, function(detail){
    val_rec <- purrr::map_dfr(detail$popts, function(.x){
      vals <- purrr::keep(.x$values, function(x_vals){
        inherits(x_vals, "nmrec_option")
      })

      purrr::map_dfr(vals, function(val){
        tibble::tibble(name = val$name, value = as.character(val$value))
      }) %>% tidyr::pivot_wider()
    })

    if (!identical(name, "theta")) {
      len_expected <- detail$size
      val_rec <- vector_to_matrix_ltri(
        as.numeric(val_rec$init), n = len_expected, type = detail$type
      )
    }
    return(val_rec)
  })

  # TODO: filter out or error if prior records found before this step/function as a whole
  if (identical(name, "theta")) {
    val_recs_fmt <- val_recs %>% purrr::list_rbind()  %>% dplyr::mutate(index = 1:n())
  }else{
    val_recs_fmt <- list(
      matrices = val_recs,
      fixed = purrr::map(records, matrix_is_fixed)
    )

    # Create combined matrix if multiple records found
    if(length(val_recs) != 1){
      val_recs_fmt$full_matrix <- as.matrix(Matrix::bdiag(val_recs))
    }
  }

  return(val_recs_fmt)
}


#' Format vector as a lower diagonal matrix
#'
#' @param vec a vector in row-major order of values.
#' @param n matrix dimension.
#' @param type type of matrix. Either "diagonal" or "block".
#'
#' @keywords internal
vector_to_matrix_ltri <- function(vec, n, type = c("diagonal", "block")) {
  type <- match.arg(type)
  mat <- matrix(0, nrow = n, ncol = n)
  if(type == "diagonal"){
    diag(mat) <- vec
  }else{
    mat[upper.tri(mat, diag = TRUE)] <- vec
  }
  return(t(mat))
}


matrix_is_fixed <- function(.record){
  any_fixed <- purrr::some(.record$values, function(rec_opt){
    if(inherits(rec_opt, "nmrec_option_nested")){
      # Handling for diagonal matrices
      purrr::some(rec_opt$values, function(rec_opt){
        inherits(rec_opt, "nmrec_option_flag") && rec_opt$name == "fixed"
      })
    }else{
      # Handling for block matrices
      inherits(rec_opt, "nmrec_option_flag") && rec_opt$name == "fixed"
    }
  })
}
```
</details>

### nmrec prototype
After putting together this prototype and discussing with @kyleam, he put together a [prototype](https://github.com/metrumresearchgroup/nmrec/compare/main...get-param) more in line with the `nmrec` code base. From my testing so far, the `nmrec` prototype Kyle put together seems to return everything I need to put together a `bbr` wrapper. 
 - I think the only thing that's missing, is a method for separating priors. Im not really sure if prior records should count as initial values, but I dont think erroring out makes sense in this case (unlike in `set_{theta,omega,sigma}` functions). I wonder if those should be an attribute (probably not) or returned in some other fashion. Im not opposed to just filtering them out, and mentioning that in the docs though.

As Kyle noted in the `TODO` sections, I think we may have to figure out better names to avoid the overlap with `bbr` functions (`get_{theta,omega,sigma}` functions). Somewhat of a shame because I like the naming convention in both cases, but obviously that's a good point given that it's quite possible a user could have both packages loaded.

### PR DESCRIPTION
**Pull request by kyleam**
Prompted by bbr's upcoming "jitter initial estimates" feature (metrumresearchgroup/bbr#632, metrumresearchgroup/bbr#635), this PR adds three functions for getting the initial estimates as a numeric vector (`THETA`) or matrix (`OMEGA` and `SIGMA`).

Series overview:

 * The first two commits are docs housekeeping.  The `set_params` typo is of course conceptually unrelated to this but is included here because the same line is touched later in this series.

 * The third commit adds a matrix utility function.

 * The remaining commits implement and extend the `extract_{theta,omega,sigma}` functions.

Closes #29.

### CODE REVIEW

**Comment by barrettk** [comment]
In my early testing of the `mark_flags` argument, I was only able to pass `mark_flags = "fix"`. Are there any other use cases (i.e. other flags) for this at the moment?

**Comment by kyleam** [comment]
> I was only able to pass `mark_flags = "fix"`

Sorry, I don't understand that.  You mean passing other flags didn't work?  Could you provide an example?

**Comment by kyleam** [comment]
> Are there any other use cases (i.e. other flags) for this at the moment?

Let's discuss after you take a look at the series.  I address this in the message of cf1448e (extract_param: support marking presence of specified flags).

**Comment by barrettk** [comment]
>Sorry, I don't understand that. You mean passing other flags didn't work? Could you provide an example?

I was more curious what options were available for this argument. After reading your updated parameter description, I see that I can now do:
```r
> .mod <- MOD1
>   ctl <- nmrec::read_ctl(get_model_path(.mod))
> nmrec::get_omega(ctl, mark_flags = c("fix","SD"))
     [,1] [,2]
[1,] 0.05   NA
[2,]   NA  0.2
attr(,"nmrec_flags")
attr(,"nmrec_flags")$fixed
      [,1]  [,2]
[1,] FALSE    NA
[2,]    NA FALSE

attr(,"nmrec_flags")$standard
      [,1]  [,2]
[1,] FALSE    NA
[2,]    NA FALSE
```

I was originally hoping I could pass `nmrec::get_omega(ctl, mark_flags = c("type"))` to get the type of matrix (diagonal or block), or even `nmrec::get_omega(ctl, mark_flags = c("size"))` to get the size. However I noticed that A) these options aren't flags, and B) it didnt seem like `nmrec:::create_param_index` checked there:

```r
> pinfo <- nmrec:::create_param_index(ctl, "omega")
> pinfo$details[[1]]$type
[1] "diagonal"
> class(pinfo$details[[1]]$type)
[1] "character"
> pinfo$details[[1]]$size
[1] 2
> class(pinfo$details[[1]]$size)
[1] "integer"
```

All that to say: are "fix" and "SD" the only valid flags that will *currently* return anything? If so, I would maybe add something to the documentation that says something like "currently supported flags are "fix" and "SD" in addition to the "any spelling is acceptable" part you have [here](https://github.com/metrumresearchgroup/nmrec/blob/955d961842580c71db71e480e0704151c3e4c897/R/extract-param.R#L27-L30).

Aside: what's the difference between "fix" and "SD"? They seem to return the same matrices in the _limited_ testing i've done.

**Comment by kyleam** [comment]
> After reading your updated parameter description, I see that I can now (pass more than just "fix") do:

"updated"?  I haven't yet pushed any changes to this PR.  I guess you're referencing the quick-and-dirty implementation I pushed earlier for you to have something to work with?  

> All that to say: are "fix" and "SD" the only valid flags that will currently return anything?

No.  Any flag option should be supported.  See the NONMEM docs on the THETA, OMEGA, and SIGMA records.

> Aside: what's the difference between "fix" and "SD"?

One is NONMEM's `FIXED` option and the other is `SD` (i.e.`STANDARD`).

**Review by barrettk — APPROVED** [review]
Went through all your tests and looks good

**Comment by kyleam** [comment]
@barrettk
> Went through all your tests and looks good

Thanks for reviewing.

For the bbr end, would you like a dev tag?

**Comment by barrettk** [comment]
> For the bbr end, would you like a dev tag

Yeah that would be great, thanks!

**Comment by kyleam** [comment]
@barrettk `0.3.0.8000` has landed.

**Pull request merged**
